config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings

  get 'pages/about'

  get 'pages/contact'

  get 'spend' => "listings#spend"

  get 'results', to: 'results#index', as: 'results'

  root 'listings#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, :all if user.role == "admin"
    can :destroy if user.role == "admin"
  else
    can :manage, Listing, user_id: user.id
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  include PgSearch
  pg_search_scope :search_everywhere, against: [:event]

  validates :event, :price, presence: true
  validates :price, numericality: { greater_than: 0 }

  belongs_to :user
# каждый список принадлежит отдному пользователю
end

app/models/role.rb
class Role < ActiveRecord::Base
#acts_as_authorization_role
has_and_belongs_to_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 validates_presence_of :name
 validates_uniqueness_of :name

  has_many :listings, dependent: :destroy
#существование списка зависит от существования пользователя который его создал,
#и для того чтобы при удалении пользователя не удалились его списки вписываем dependent destroy
  ROLES = %w[admin author]

  ROLES.freeze

  def role_symbols
    [role.to_sym]
  end
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :roles,
      :role)
    }

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:spend, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  respond_to :html

def spend
    @listings = Listing.where(user: current_user)
  end

  def index
    @listings = Listing.all
    respond_with(@listings)
  end

  def show
    respond_with(@listing)
  end

  def new
    @listing = Listing.new
    respond_with(@listing)
  end

  def edit
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @listing.save
    respond_with(@listing)
  end

  def update
    @listing.update(listing_params)
    respond_with(@listing)
  end

  def destroy
    @listing.destroy
    respond_with(@listing)
  end

  private
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:date, :event, :price)
    end

    def check_user
    # if current_user != @listing.user
     #  redirect_to root_url, alert: "you are not acces to this listing"
    #end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @search_results = Listing.search_everywhere(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_flash_messages.html.erb
<div>  
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>  

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">GreedIsGood</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Manage listings", spend_path %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greedisgood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">

<%= form_tag results_path, method: :get, role: 'search' do %>
  <%= text_field_tag :query, params[:query], placeholder: 'Event' %>
  <%= submit_tag "Искать", name: nil %>
<% end %>

<%= render 'layouts/flash_messages' %>

	<%= yield %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.input :date, as: :string %>
  <%= f.input :event %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<h1>Spend Listings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>event</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.date %></td>
        <td><%= listing.event %></td>
        <td><%= listing.price %></td>
        <td><%= link_to 'Show', listing, class: "btn btn-link" %></td>

        <% if can? :update, @listing %>
          <td><%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %></td>
        <% end %>

        <% if can? :destroy, @listing %>
          <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @listing.date %>
</p>

<p>
  <strong>event:</strong>
  <%= @listing.event %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<% if can? :update, @listing %>
	<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %>
<% end %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/spend.html.erb
<h1>Spend Listings</h1>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

<table class="table table-striped table-bordered">
    <tr>
      <th class="center">Date</th>
      <th class="center">event</th>
      <th class="center">Price</th>
      <th class="center">Action</th>
    </tr>


    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.date %></td>
        <td><%= listing.event %></td>
        <td><%= listing.price %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>

          <% if can? :update, @listing %>
            <li><%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %></li>
          <% end %>

          <% if can? :destroy, @listing %>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
          <% end %>

          </ul>
        </div>
      </td>
		</tr>
  <% end %>
</table>

app/views/pages/about.html.erb
<h1>Денежный калькулятор </h1>
<p>Проект предполагает подсчет денежных средств </p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/results/index.html.erb
<h3>Результаты поиска по запросу <em><%= params[:query]%></em></h3>
<% @search_results.each do |result| %>
  <h4><%= link_to result.event, result %></h4>
  <div><%= result.event.html_safe %></div>
  <hr>
<% end %>